#' Profile the memory requirements of a cost surface (with origins / destinations) to estimate optimum parameters. Currently under development. Not exported.
#'
#' Profiles the memory resources and processing time required to calculate least-cost paths using a given cost surface and origins / destinations.
#'
#' @param cs \code{conductanceMatrix}
#'
#' @param cost_distance \code{logical} if TRUE computes total accumulated cost from origin to the destinations. FALSE (default)
#'
#' @author Barney Harris
#'
#' @return \code{sf} returns object of class \code{conductanceMatrixProfile}
#'
#' @examples
#'
#'
#' r <- terra::rast(system.file("extdata/SICILY_1000m.tif", package="leastcostpath"))
#'
#' slope_cs <- create_slope_cs(x = r, cost_function = "tobler", neighbours = 4)
#'
#' cs_profile <- profile_cs(cs = slope_cs)

# cs <- qs::qread('~/git/freg/lcp_data_big/slope_cs_n16_exag.qs')
# cs$cs_dem <- unwrap(cs$cs_dem)
# cs$cppRoutingGraph <- qs::qread('~/git/freg/lcp_data_big/cppRoutingGraph.qs')
# grid_sizes=c(10,15,25,32,46)
#
# dput(c(10,15,25,32,46)^2)

profile_cs_grid <- function(
  cs,
  cost_distance,
  grid_sizes = c(10, 15, 25, 32, 46)
) {
  # aim to explore the average length / size of routes generated by using a grid
  # of points covering the whole cs. Average values can then be used to limit the
  # number of routes generated to stay within vector memory size limits.
  profiles_out <- list()

  for (grid_size in grid_sizes) {
    # generate grid if no origins OR destinations supplied, or not enough supplied
    origin <-
      spatSample(
        cs$cs_dem,
        size = grid_size,
        method = 'regular',
        na.rm = T,
        as.points = T,
        cells = T
      )

    locations <- list(origin = origin)
    locations_names <- names(locations)
    names(locations_names) <- names(locations)

    locations_cells <-
      lapply(
        locations_names,
        FUN = \(x) {
          check_duplicate_locations(
            locations = locations[[x]],
            locations_name = x,
            cs = cs
          )
        }
      )

    # will default to origin * origin if no destinations supplied
    max_length_locations <- length(locations_cells)

    theoretical_total_paths <-
      length(locations_cells[[1]]) *
      length(locations_cells[[max_length_locations]])

    message(
      paste0(
        'Profiling using ',
        theoretical_total_paths,
        ' least-cost paths... '
      )
    )

    st <- Sys.time()
    lcp_graph <-
      cppRouting::get_multi_paths(
        cs$cppRoutingGraph,
        from = locations_cells[[1]],
        to = locations_cells[[max_length_locations]],
        long = T
      )

    # construct least-cost path vector lines -----
    message('building vector data from route nodes...')
    coords <-
      terra::xyFromCell(cs$cs_dem, as.integer(lcp_graph$node)) |>
      as.data.frame()

    coords_node <-
      coords |>
      mutate(node = lcp_graph$node)

    lcp_graph_coords <-
      lcp_graph |>
      mutate(from_to = paste0(from, '_', to)) |>
      dplyr::bind_cols(coords)

    lcp_graph_coords_dist <-
      lcp_graph_coords |>
      distinct(from_to)

    lcp_graph_geom <-
      lcp_graph_coords |>
      group_by(from_to) |>
      mutate(
        object = cur_group_id(),
        num_nodes = n()
      ) |>
      ungroup() |>
      mutate(part = 1, hole = 0) |>
      dplyr::select(c(object, part, x, y, hole)) |>
      as.matrix()

    lcps <-
      terra::vect(
        x = lcp_graph_geom,
        crs = terra::crs(cs$cs_dem),
        type = 'lines',
        atts = lcp_graph_coords_dist
      )
    en_diff <- as.numeric(difftime(Sys.time(), st, units = 'secs'))

    actual_total_paths <-
      nrow(lcp_graph_coords_dist)

    if (actual_total_paths < theoretical_total_paths) {
      message(
        paste0(
          theoretical_total_paths - actual_total_paths,
          ' least-cost paths could not be calculated.',
          ' Are some locations inaccessible i.e. surrounded by or near to NaN cells?'
        )
      )
    } else {
      message('All least-cost paths succesfully calculated.')
    }

    # get euclidean distances of from to nodes
    lcps_nodes <- lcps |>
      as.data.frame() |>
      tidyr::separate_wider_delim(
        from_to,
        '_',
        names = c('from', 'to')
      )

    from_p <-
      vect(
        xyFromCell(cs$cs_dem, as.integer(lcps_nodes$from)),
        crs = crs(cs$cs_dem)
      )
    to_p <-
      vect(
        xyFromCell(cs$cs_dem, as.integer(lcps_nodes$to)),
        crs = crs(cs$cs_dem)
      )
    p_dists <- distance(from_p, to_p)

    total_route_euclidean_distance <- sum(p_dists)
    average_route_euclidean_distance <- mean(p_dists)
    # infer resolution of grid
    nearby_points <- terra::nearby(origin, k = 1)
    grid_res <- lapply(1:nrow(origin), \(.x) {
      distance(
        origin[nearby_points[.x, 1], ],
        origin[nearby_points[.x, 2], ]
      )
    }) |>
      unlist() |>
      mean()

    # calc summary stats based on lcps
    total_route_length <- nrow(lcp_graph)
    # average_route_length <- total_route_length/actual_total_paths
    total_route_size <- object.size(lcp_graph)
    # average_route_size <- total_route_size/actual_total_paths
    # average values don't appear to offer much insight !

    results_df <- tibble(
      `Inferred grid resolution` = grid_res,
      `No. least-cost paths attempted` = theoretical_total_paths,
      `No. least-cost paths generated` = actual_total_paths,
      `All routes vector length` = total_route_length,
      `All routes summed euclidean distance` = total_route_euclidean_distance,
      `All routes vector size (Mb)` = as.numeric(gsub(
        "Mb",
        "",
        format(total_route_size, 'Mb')
      )),
      `All routes processing time (secs)` = en_diff
    )

    profiles_out[[as.character(grid_size)]] <- results_df
  }

  # model memory and time ----
  profiles_out_df <- bind_rows(profiles_out)

  ## memory model ----
  m_size_lcps <- lm(
    `No. least-cost paths generated` ~ `All routes vector size (Mb)`,
    data = profiles_out_df
  )
  m_size_lcps_summary <- summary(m_size_lcps)

  preds <-
    bind_cols(
      profiles_out_df,
      predict(m_size_lcps, profiles_out_df, interval = 'confidence')
    )

  (m_size_lcps_p <-
    ggplot2::ggplot(
      preds,
      ggplot2::aes(
        x = `All routes vector size (Mb)`,
        y = `No. least-cost paths generated`
      )
    ) +
    ggplot2::geom_ribbon(ggplot2::aes(ymin = lwr, ymax = upr), alpha = 0.3) +
    ggplot2::geom_point() +
    ggplot2::theme_bw())

  memory_routes <-
    tibble(
      `All routes vector size (Mb)` = c(
        mem.maxVSize() / 2,
        1:10 * mem.maxVSize()
      )
    )

  memory_routes$`No. least-cost paths generated` <-
    predict(m_size_lcps, newdata = memory_routes)

  m_lcps_size <- lm(
    `All routes vector size (Mb)` ~ `No. least-cost paths generated`,
    data = profiles_out_df
  )
  m_lcps_size_summary <- summary(m_lcps_size)

  planned_routes <-
    (length(locations_cells$origin) *
      length(locations_cells$destination)) -
    min(length(locations_cells$origin), length(locations_cells$destination))

  ## time model ----
  profiles_out_df <- profiles_out_df[
    order(profiles_out_df$`No. least-cost paths generated`),
  ]
  weights <- # helps reduce under-predictions
    profiles_out_df$`All routes processing time (secs)` /
    max(profiles_out_df$`All routes processing time (secs)`)

  m_time_lcps <-
    lm(
      `All routes processing time (secs)` ~ log(
        `No. least-cost paths generated`
      ),
      data = profiles_out_df,
      weights = weights
    )
  m_time_lcps_summary <- summary(m_time_lcps)

  preds <-
    bind_cols(
      profiles_out_df,
      predict(m_time_lcps, profiles_out_df, interval = 'confidence')
    )

  (m_time_lcps_p <-
    ggplot2::ggplot(
      preds,
      ggplot2::aes(
        x = `No. least-cost paths generated`,
        y = `All routes processing time (secs)`
      )
    ) +
    ggplot2::geom_ribbon(ggplot2::aes(ymin = lwr, ymax = upr), alpha = 0.3) +
    ggplot2::geom_point())

  memory_routes$`All routes processing time (secs)` <- predict(
    m_time_lcps,
    newdata = memory_routes
  )

  ## plan ----
  memory_routes$`Planned No. least-cost paths generated` <- planned_routes

  memory_routes_plan <-
    memory_routes |>
    mutate(
      planned_tasks = ceiling(
        `Planned No. least-cost paths generated` /
          `No. least-cost paths generated`
      ),
      `Planned All routes processing time (secs)` = planned_tasks *
        `All routes processing time (secs)`,
      `Planned All routes processing time (hours)` = `Planned All routes processing time (secs)` /
        3600
    ) |>
    mutate(
      across(
        .cols = `Planned All routes processing time (hours)`,
        .fns = list(
          `with two nodes` = \(x) x / 2,
          `with four nodes` = \(x) x / 4,
          `with six nodes` = \(x) x / 6,
          `with eight nodes` = \(x) x / 8,
          `with ten nodes` = \(x) x / 10
        ),
        .names = '{.col} {.fn}'
      )
    )

  plat <- sessionInfo()$platform
  machine <- Sys.info()[5]

  profile_out_list <-
    list(
      `LCP Plan` = memory_routes_plan,
      `Size and number of lcps model` = list(
        Summary = m_size_lcps_summary,
        Plot = m_size_lcps_p
      ),
      `Number of lcps and time model` = list(
        Summary = m_time_lcps_summary,
        Plot = m_time_lcps_p
      ),
      `Time date of profile` = Sys.time(),
      `Profile system platform` = plat,
      `Profile system machine` = machine
    )

  profile_out_list <- class('csProfileGrid')
  cs$csProfileGrid <- profile_out_list

  return(cs)
}
