#' Profile the memory requirements of a cost surface (with origins / destinations) to estimate optimum parameters. Currently under development. Not exported.
#'
#' Profiles the memory resources and processing time required to calculate least-cost paths using a given cost surface and origins / destinations.
#'
#' @param cs \code{conductanceMatrix}
#'
#' @param cost_distance \code{logical} if TRUE computes total accumulated cost from origin to the destinations. FALSE (default)
#'
#' @author Barney Harris
#'
#' @return \code{sf} returns object of class \code{conductanceMatrixProfile}
#'
#'
#' @examples
#'
#'
#' r <- terra::rast(system.file("extdata/SICILY_1000m.tif", package="leastcostpath"))
#'
#' slope_cs <- create_slope_cs(x = r, cost_function = "tobler", neighbours = 4)
#'
#' cs_profile <- profile_cs(cs = slope_cs)

profile_cs_custom <-
  function(
    cs,
    origin,
    destination,
    route_profile_targets = c(100, 225, 625, 1024, 2116),
    iterations = 3
  ) {
    # aim to explore the average length / size of routes generated by using a grid
    # of points covering the whole cs. Average values can then be used to limit the
    # number of routes generated to stay within vector memory size limits.
    # profiles_out <- list()
    # route_profile_target <- route_profile_targets[1]
    # route_profile_target <- 500000
    # iterations <- 1
    for (route_profile_target in route_profile_targets) {
      required_theoretical_paths <-
        route_profile_target + (route_profile_target * (iterations / 10))

      if (any(c(!is.null(origin), !is.null(destination)))) {
        locations <- list(origin = origin)
        if (!is.null(destination)) {
          locations$destination <- destination
        }
        locations_names <- names(locations)
        names(locations_names) <- names(locations)

        locations_cells <-
          lapply(
            locations_names,
            FUN = \(x) {
              check_duplicate_locations(
                locations = locations[[x]],
                locations_name = x,
                cs = cs
              )
            }
          )

        # will default to origin * origin if no destinations supplied
        max_length_locations <- length(locations_cells)

        theoretical_total_paths <-
          length(locations_cells[[1]]) *
          length(locations_cells[[max_length_locations]])

        if (theoretical_total_paths < required_theoretical_paths) {
          message(
            'Not enough origins / destinations to meet route profile target and number of iterations...'
          )
          message(
            'Memory profiling is probably not required for this number of routes'
          )
          message(
            'Decrease `route_profile_target` or `iterations` to use these user-supplied origin / destinations, or use `profile_cs()` to generate generalised requirements for this cost surface.'
          )
          message('Defaulting to randomly generated points...')
          return(NULL)
        }
      }

      num_of_each_locations <- ceiling(sqrt(route_profile_target))
      # sub sample given origins / destinations
      # x <- 1
      # iterations <- 1

      results <- lapply(1:iterations, \(x) {
        locations_cells_smp <-
          lapply(locations_cells, \(x) {
            if (length(x) > num_of_each_locations) {
              sample(x, size = num_of_each_locations)
            } else {
              x
            }
          })

        # will default to origin * origin if no destinations supplied
        max_length_locations <- length(locations_cells_smp)

        theoretical_total_paths <-
          length(locations_cells_smp[[1]]) *
          length(locations_cells_smp[[max_length_locations]])

        message(
          paste0(
            'Profiling, attempting ',
            theoretical_total_paths,
            ' least-cost paths... '
          )
        )
        message(
          paste0(
            'Using ',
            RcppParallel::defaultNumThreads(),
            ' threads and 1 worker...'
          )
        )

        st <- Sys.time()

        # prof_routing <-
        #   profmem::profmem({
        lcp_graph <-
          cppRouting::get_multi_paths(
            cs$cppRoutingGraph,
            from = locations_cells_smp[[1]],
            to = locations_cells_smp[[max_length_locations]],
            long = T
          )
        # })

        head(lcp_graph)

        test_ext <- ext(buffer(vect(xyFromCell(cs$cs_dem, 16834540)), 1000))
        cs_dem_clip <- crop(cs$cs_dem, test_ext)
        test_pol <- as.polygons(cs_dem_clip, round = F, aggregate = F)
        test_pol$cell_num <- cells(cs$cs_dem, test_ext)
        plot(cs_dem_clip)
        text(test_pol, "cell_num", col = 'white')

        `%!in%` <- Negate(`%in%`)

        lcp_graph_dt <- data.table::as.data.table(lcp_graph)
        lcp_graph_dt[, seq_id := 1:.N]
        lcp_graph_dt[, next_node := data.table::shift(node, -1L)]

        lcp_graph_dt_adjacent <-
          lcp_graph_dt[
            next_node %in%
              terra::adjacent(cs$cs_dem, as.integer(node)),
          ]

        lcp_graph_dt_nonadjacent <-
          lcp_graph_dt[
            next_node %!in%
              terra::adjacent(cs$cs_dem, as.integer(node)),
          ]

        node_counts <- table(lcp_graph$node)
        lcp_density <- rast(cs$cs_dem)

        terra::set.values(lcp_density, cells = cells(cs$cs_dem), values = 0)
        terra::set.values(
          lcp_density,
          cells = as.integer(names(node_counts)),
          values = as.integer(node_counts)
        )

        writeRaster(lcp_density, 't.tif')
        lcp_density_ag <- terra::aggregate(lcp_density, 2, fun = 'max')
        writeRaster(lcp_density_ag, 't_ag_2.tif')

        print(difftime(Sys.time(), st, units = 'secs'))
        message('finished routing! Connecting to DuckDB instance...')
        if (file.exists('lcp_graph.duckdb')) {
          file.remove('lcp_graph.duckdb')
        }

        con <- DBI::dbConnect(duckdb::duckdb(), dbdir = 'lcp_graph.duckdb')
        res <- duckdb::dbSendQuery(
          con,
          "SELECT current_setting('threads') AS threads;"
        )
        print(difftime(Sys.time(), st, units = 'secs'))
        message(
          'Connected! Running DuckDB using ',
          paste0(duckdb::dbFetch(res), ' threads...')
        )

        duckdb::dbSendQuery(con, 'INSTALL spatial; LOAD spatial;')
        duckdb::dbSendQuery(con, 'INSTALL parquet; LOAD parquet;')

        print(difftime(Sys.time(), st, units = 'secs'))
        message('writing paths to duckdb table...')
        duckdb::dbWriteTable(
          con,
          name = 'lcp_graph',
          value = lcp_graph,
          overwrite = T
        )
        print(difftime(Sys.time(), st, units = 'secs'))
        message('retrieving and writing cell coordinates to duckdb table...')
        coords <-
          terra::xyFromCell(cs$cs_dem, as.integer(unique(lcp_graph$node))) |>
          as.data.frame() |>
          mutate(node = unique(lcp_graph$node))
        duckdb::dbWriteTable(
          con,
          name = 'lcp_coords',
          value = coords,
          overwrite = T
        )

        catKey <- '_'
        q <- glue::glue_sql(
          '
        DROP TABLE IF EXISTS lcp_graph_coords;
        CREATE TABLE lcp_graph_coords AS SELECT *
        FROM lcp_graph
        JOIN lcp_coords
        ON lcp_graph.node = lcp_coords.node;
        
        ALTER TABLE lcp_graph_coords ADD COLUMN from_to TEXT;
        UPDATE lcp_graph_coords SET from_to = "from" || {catKey} || "to";
        
        ALTER TABLE lcp_graph_coords DROP COLUMN "from";
        ALTER TABLE lcp_graph_coords DROP COLUMN "to";
        
        ',
          .con = con
        )
        print(difftime(Sys.time(), st, units = 'secs'))
        message('joining coords to paths and grouping by path id...')
        res <- duckdb::dbSendQuery(con, q)

        q <- glue::glue_sql(
          '
        DROP TABLE IF EXISTS lcp_graph_points;
        CREATE TABLE lcp_graph_points AS 
        SELECT *, ST_Point(x, y) AS geom
        FROM lcp_graph_coords;

        ',
          .con = con
        )
        print(difftime(Sys.time(), st, units = 'secs'))
        message('converting to geometries...')
        res <- duckdb::dbSendQuery(con, q)

        q <- glue::glue_sql(
          '
        DROP TABLE IF EXISTS lcp_points_agg;
        CREATE TABLE lcp_points_agg AS
        SELECT from_to, array_agg(geom ORDER BY rowid) AS agg_geom FROM lcp_graph_points GROUP BY from_to;
        
        DROP TABLE IF EXISTS lcp_lines;
        CREATE TABLE lcp_lines AS
        SELECT ST_MakeLine(agg_geom) as line_geom FROM lcp_points_agg;
        
        '
        )
        print(difftime(Sys.time(), st, units = 'secs'))
        message(
          'aggregating points by path and converting to line geometries...'
        )
        res <- duckdb::dbSendQuery(con, q)

        res <-
          duckdb::dbSendQuery(
            con,
            'SELECT COUNT() AS total_lines FROM lcp_lines;'
          )
        total_lines <- duckdb::dbFetch(res)

        res <-
          duckdb::dbSendQuery(
            con,
            'SELECT ST_AsText(ST_Envelope_Agg(line_geom)) AS line_bbox FROM lcp_lines;'
          )

        total_lines_bbox_pol <- vect(duckdb::dbFetch(res)$line_bbox)
        total_lines_bbox <- ext(total_lines_bbox_pol)
        total_lines_bbox_ogr <- c(
          total_lines_bbox[1],
          total_lines_bbox[3],
          total_lines_bbox[2],
          total_lines_bbox[4]
        )

        q <- glue::glue_sql(
          "
          COPY (
              SELECT *
              FROM lcp_lines)
          TO 'lcp_lines.parquet'
          (FORMAT 'parquet', COMPRESSION 'zstd', OVERWRITE_OR_IGNORE TRUE, PER_THREAD_OUTPUT TRUE);
          "
        )
        print(difftime(Sys.time(), st, units = 'secs'))
        message(glue::glue('writing {total_lines} lines as geoparquet file...'))
        res <- duckdb::dbSendQuery(con, q)

        line_partitions <-
          list.files(file.path(getwd(), 'lcp_lines.parquet'), full.names = T)

        print(difftime(Sys.time(), st, units = 'secs'))
        message('rasterizing line geometries...')
        lapply(line_partitions, \(x) {
          tifOut <- file.path(dirname(x), gsub('parquet', 'tif', basename(x)))
          system(glue::glue(
            "gdal_rasterize -te {paste0(total_lines_bbox_ogr,collapse=' ')} ",
            "-tr {paste0(res(cs$cs_dem),collapse=' ')} ",
            "-burn 1 -init 0 -add -at {x} {tifOut}"
          ))
        })
        proc_time <- difftime(Sys.time(), st, units = 'secs')
        print(proc_time)
        message('finished!')

        # doesn't work with parquet ??
        # gdalUtilities::gdal_rasterize(
        #   src_datasource = 'data_0.parquet',
        #   dst_filename = 'out2.tif',
        #   te = total_lines_bbox_ogr,
        #   tr = paste0(res(cs$cs_dem)),
        #   burn = 1,
        #   init = 0,
        #   add = T,
        #   at = T
        # )

        # construct least-cost path vector lines -----
        message('building vector data from route nodes...')

        message('retrieving coordinates...')
        prof_data_frame_processing <-
          profmem::profmem({
            coords <-
              terra::xyFromCell(cs$cs_dem, as.integer(lcp_graph$node)) |>
              as.data.frame()

            coords_node <-
              coords |>
              mutate(node = lcp_graph$node)

            lcp_graph_coords <-
              lcp_graph |>
              mutate(from_to = paste0(from, '_', to)) |>
              dplyr::bind_cols(coords)

            lcp_graph_coords_dist <-
              lcp_graph_coords |>
              distinct(from_to)

            lcp_graph_geom <-
              lcp_graph_coords |>
              group_by(from_to) |>
              mutate(
                object = cur_group_id(),
                num_nodes = n()
              ) |>
              ungroup() |>
              mutate(part = 1, hole = 0) |>
              dplyr::select(c(object, part, x, y, hole)) |>
              as.matrix()

            lcps <-
              terra::vect(
                x = lcp_graph_geom,
                crs = terra::crs(cs$cs_dem),
                type = 'lines',
                atts = lcp_graph_coords_dist
              )
          })

        prof_dt_processing <-
          profmem::profmem({
            # convert to dt
            lcp_graph_dt <-
              data.table::as.data.table(lcp_graph)
            rm(lcp_graph)
            gc()

            # get dt of coords
            cell_dt <-
              as.data.frame(cs$cs_dem, cells = T, xy = T, row.names = F)[,
                1:3
              ] |>
              rename('node' = cell) |>
              mutate(node = as.character(node)) |>
              data.table::as.data.table()

            lcp_graph_coords <-
              cell_dt[lcp_graph_dt, on = 'node'] |>
              _[, from_to := paste0(from, '_', to)]

            lcp_graph_coords[,
              `:=`(
                object = .GRP # Equivalent to cur_group_id()
              ),
              by = from_to
            ]

            # Additional mutations
            lcp_graph_coords[, `:=`(part = 1, hole = 0)]

            # Select specific columns and convert to matrix
            lcp_graph_geom <- as.matrix(lcp_graph_coords[, .(
              object,
              part,
              x,
              y,
              hole
            )])

            lcps <-
              terra::vect(
                x = lcp_graph_geom,
                crs = terra::crs(cs$cs_dem),
                type = 'lines',
                atts = lcp_graph_coords_dist
              )
          })

        prof_arrow_processing <-
          profmem::profmem({
            lcp_graph_arrow <- arrow::arrow_table(lcp_graph)

            cell_coords_arrow <-
              as.data.frame(cs$cs_dem, cells = T, xy = T, row.names = F)[,
                1:3
              ] |>
              rename('node' = cell) |>
              mutate(node = as.character(node)) |>
              arrow::arrow_table()

            lcp_graph_from_to <-
              lcp_graph_arrow |>
              mutate(from_to = paste0(from, '_', to))

            lcp_graph_from_to_distinct_df <-
              lcp_graph_from_to_distinct |>
              collect()

            lcp_graph_from_to_distinct_arrow <-
              arrow::arrow_table(
                from_to = lcp_graph_from_to_distinct_df$from_to,
                object = 1:nrow(lcp_graph_from_to_distinct_df)
              )

            lcp_graph_geom <-
              lcp_graph_from_to |>
              left_join(
                cell_coords_arrow,
                by = 'node'
              ) |>
              left_join(
                lcp_graph_from_to_distinct_arrow,
                by = 'from_to'
              ) |>
              group_by(object) |>
              mutate(part = 1, hole = 0) |>
              dplyr::select(c(object, part, x, y, hole)) |>
              collect() |>
              as.matrix()

            lcps <-
              terra::vect(
                x = lcp_graph_geom,
                crs = terra::crs(cs$cs_dem),
                type = 'lines',
                atts = lcp_graph_coords_dist
              )
          })

        prof_vect <-
          profmem::profmem({
            lcps <-
              terra::vect(
                x = lcp_graph_geom,
                crs = terra::crs(cs$cs_dem),
                type = 'lines',
                atts = lcp_graph_coords_dist
              )
          })

        en_diff <- as.numeric(difftime(Sys.time(), st, units = 'secs'))

        actual_total_paths <-
          nrow(lcp_graph_coords_dist)

        if (actual_total_paths < theoretical_total_paths) {
          message(
            paste0(
              theoretical_total_paths - actual_total_paths,
              ' least-cost paths could not be calculated.',
              ' Are some locations inaccessible i.e. surrounded by or near to NaN cells?'
            )
          )
        } else {
          message('All least-cost paths succesfully calculated.')
        }

        # get euclidean distances of from to nodes
        lcps_nodes <- lcps |>
          as.data.frame() |>
          tidyr::separate_wider_delim(
            from_to,
            '_',
            names = c('from', 'to')
          )

        from_p <-
          vect(
            xyFromCell(cs$cs_dem, as.integer(lcps_nodes$from)),
            crs = crs(cs$cs_dem)
          )
        to_p <-
          vect(
            xyFromCell(cs$cs_dem, as.integer(lcps_nodes$to)),
            crs = crs(cs$cs_dem)
          )
        p_dists <- distance(from_p, to_p)

        total_route_euclidean_distance <- sum(p_dists)
        average_route_euclidean_distance <- mean(p_dists)

        # calc summary stats based on lcps
        total_route_length <- nrow(lcp_graph)
        # average_route_length <- total_route_length/actual_total_paths
        total_route_size <- object.size(lcp_graph)
        # average_route_size <- total_route_size/actual_total_paths
        # average values don't appear to offer much insight !
        # mem_list <-
        #   list(`Profile for get_multi_paths()` = prof_get_multi_paths,
        #        `Profile for data frame processing` = prof_data_frame_processing,
        #        `Profile for vect()` = prof_vect
        #        )
        prof <-
          read.delim(
            'routingProf.out',
            sep = ':',
            header = F,
            col.names = c('bytes', 'call')
          )
        mem_df <-
          bind_rows(mem_list, .id = 'routine') |>
          group_by(routine) |>
          summarise(
            `Max (Mb)` = max(bytes, na.rm = T) / 1000000,
            `Sum (Mb)` = sum(bytes, na.rm = T) / 1000000
          ) |>
          tidyr::pivot_wider(
            names_from = 'routine',
            values_from = c(`Max (Mb)`, `Sum (Mb)`)
          )

        results_df <- tibble(
          `No. least-cost paths attempted` = theoretical_total_paths,
          `No. least-cost paths generated` = actual_total_paths,
          `All routes vector length` = total_route_length,
          `All routes summed euclidean distance` = total_route_euclidean_distance,
          `All routes vector size (Mb)` = as.numeric(gsub(
            "Mb",
            "",
            format(total_route_size, 'Mb')
          )),
          `All routes processing time (secs)` = en_diff
        ) |>
          bind_cols(mem_df)

        return(results_df)
      })

      results_df <- bind_rows(results)
      profiles_out[[as.character(route_profile_target)]] <- results_df
    }

    # model memory and time ----
    profiles_out_df <- bind_rows(profiles_out)

    # profiles_out_df <- readRDS('~/Downloads/afbig_profiles_out_df.RDS')
    ## memory model ----
    m_size_lcps <- lm(
      `No. least-cost paths generated` ~ `All routes vector size (Mb)`,
      data = profiles_out_df
    )
    m_size_lcps_summary <- summary(m_size_lcps)

    preds <-
      bind_cols(
        profiles_out_df,
        predict(m_size_lcps, profiles_out_df, interval = 'confidence')
      )

    (m_size_lcps_p <-
      ggplot2::ggplot(
        preds,
        ggplot2::aes(
          x = `All routes vector size (Mb)`,
          y = `No. least-cost paths generated`
        )
      ) +
      ggplot2::geom_ribbon(ggplot2::aes(ymin = lwr, ymax = upr), alpha = 0.3) +
      ggplot2::geom_point() +
      ggplot2::theme_bw())

    # check vsize has limit
    sys.mem.maxVSize <-
      ifelse(!is.finite(mem.maxVSize()), 16384, mem.maxVSize())

    memory_routes <-
      tibble(
        `All routes vector size (Mb)` = c(
          sys.mem.maxVSize / 2,
          1:10 * sys.mem.maxVSize
        )
      )

    memory_routes$`No. least-cost paths generated` <-
      predict(m_size_lcps, newdata = memory_routes)

    m_lcps_size <- lm(
      `All routes vector size (Mb)` ~ `No. least-cost paths generated`,
      data = profiles_out_df
    )
    m_lcps_size_summary <- summary(m_lcps_size)

    ## time ----
    profiles_out_df <- profiles_out_df[
      order(profiles_out_df$`No. least-cost paths generated`),
    ]
    weights <- # helps reduce under-predictions
      profiles_out_df$`All routes processing time (secs)` /
      max(profiles_out_df$`All routes processing time (secs)`)

    m_time_lcps <-
      lm(
        `All routes processing time (secs)` ~ log(
          `No. least-cost paths generated`
        ),
        data = profiles_out_df,
        weights = weights
      )
    m_time_lcps_summary <- summary(m_time_lcps)

    preds <-
      bind_cols(
        profiles_out_df,
        predict(m_time_lcps, profiles_out_df, interval = 'confidence')
      )

    (m_time_lcps_p <-
      ggplot2::ggplot(
        preds,
        ggplot2::aes(
          x = `No. least-cost paths generated`,
          y = `All routes processing time (secs)`
        )
      ) +
      ggplot2::geom_ribbon(ggplot2::aes(ymin = lwr, ymax = upr), alpha = 0.3) +
      ggplot2::geom_point())

    memory_routes$`All routes processing time (secs)` <- predict(
      m_time_lcps,
      newdata = memory_routes
    )

    ## plan ----
    planned_routes <-
      (length(locations_cells$origin) *
        length(locations_cells$destination)) -
      min(length(locations_cells$origin), length(locations_cells$destination))

    memory_routes$`Planned No. least-cost paths generated` <- planned_routes

    memory_routes_plan <-
      memory_routes |>
      mutate(
        `Planned tasks` = ceiling(
          `Planned No. least-cost paths generated` /
            `No. least-cost paths generated`
        ),
        `Planned All routes processing time (secs)` = `Planned tasks` *
          `All routes processing time (secs)`,
        `Planned All routes processing time (hours)` = `Planned All routes processing time (secs)` /
          3600
      ) |>
      mutate(
        across(
          .cols = `Planned All routes processing time (hours)`,
          .fns = list(
            `with two nodes` = \(x) x / 2,
            `with four nodes` = \(x) x / 4,
            `with six nodes` = \(x) x / 6,
            `with eight nodes` = \(x) x / 8,
            `with ten nodes` = \(x) x / 10
          ),
          .names = '{.col} {.fn}'
        )
      )

    plat <- sessionInfo()$platform
    machine <- as.character(Sys.info()[5])

    profile_out_list <-
      list(
        `Profiles out` = profiles_out_df,
        `LCP Plan` = memory_routes_plan,
        `Size and number of lcps model` = list(
          Summary = m_size_lcps_summary,
          Plot = m_size_lcps_p
        ),
        `Number of lcps and time model` = list(
          Summary = m_time_lcps_summary,
          Plot = m_time_lcps_p
        ),
        `Time date of profile` = Sys.time(),
        `Profile system platform` = plat,
        `Profile system machine` = machine
      )

    class(profile_out_list) <- c('csProfileCustom', 'list')
    cs$csProfileCustom <- profile_out_list
    class(cs) <- c('csProfileCustomPlan', 'list')
    return(cs)
  }

#TODO:  create cs_trim() function -- uses origin and dest on resampled raster and cost surface to identify
# geographic space likely involved in paths. Trims original cost surface graph.
